# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/alps/XY_C15_TFT_LFLT/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),XY_C15_TFT_LFLT)

endif
